# Generated by Django 5.0.4 on 2024-04-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='created_at',
        ),
    ]
