# Generated by Django 5.0.4 on 2024-04-23 13:35

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posts_author_posts_content_posts_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Reviews'), (2, 'Tutoriais'), (3, 'Dicas'), (4, 'Resultados'), (5, 'Pessoal')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
