# Generated by Django 5.0.4 on 2024-04-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_posts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
